### ISSUE TITLE
Unary ! and Logical not

### ISSUE THREAD

**Issue by SolarWolf-Code** [serqlane/serqlane#61]
The unary ! operator seems to be using `not`:
https://github.com/serqlane/serqlane/blob/1d86647f7cc261e882adeafc6b6f1b8008966bcb/serqlane/grammar.lark#L95-L98

If we are going with C style unary operators they should be as follows:
- `-` unary minus
- `++` increment
- `--` decrement
- `!` not
- etc..

Additionally, it seems like we do not have a logical way to specify not, which is possible the cause of unary not being assigned as `not`. These are the only two I believe:
https://github.com/serqlane/serqlane/blob/1d86647f7cc261e882adeafc6b6f1b8008966bcb/serqlane/grammar.lark#L84-L85

The prevent us from being able to do something like:
``` rust
let x = 10
let y = 20
if not x < y {
    dbg("x is not less than y")
}
```
As it causes the following error:
`ValueError: tree=Tree(Token('RULE', 'unary_expression'), [Tree(Token('RULE', 'not'), []), Tree(Token('RULE', 'expression'), [Tree(Token('RULE', 'identifier'), [Token('__ANON_5', 'x')])])])`

**Comment by SirOlaf** [comment]
Addressed by #96
